---
- name: Source Installation for base system
  hosts: slave
  remote_user: perfbhi
  tasks:
       - name: Create base dir for source compilation
         file:
           path: "/data1/apps-install"
           owner: perfbhi
           group: perfbhi
           mode: 0777
           state: directory
       
       - name: Add additional bash_profile entries
         lineinfile:
           path: /home/perfbhi/.bash_profile
           line: 'PATH=/data1/apps-install/bin:$PATH' 
       
       - name: Add additional bash_profile entries  
         lineinfile:  
           path: /home/perfbhi/.bash_profile
           line: 'LD_LIBRARY_PATH=/data1/apps-install/lib:/data1/apps-install/lib64:$LD_LIBRARY_PATH'

       
       - name: Source bash_profile
         shell: source "/home/perfbhi/.bash_profile"
         args:
           executable: /bin/bash
    
       - name: Create remote dir for copying Source packages
         file:
           path: "/data1/Source"
           owner: perfbhi
           group: perfbhi
           mode: 0777
           state: directory

       - name: Copy Pen package
         copy:
           src: /home/perfbhi/ansible/Source/pen-0.18.0.tar.gz
           dest: /data1/Source/pen-0.18.0.tar.gz
           owner: perfbhi
           group: perfbhi
           mode: 0755

       - name: Untar Pen Package
         unarchive:
           src: /data1/Source/pen-0.18.0.tar.gz
           dest: /data1/Source/
           remote_src: yes

       - name: Compile Pen package
         command: "{{item}} chdir=/data1/Source/pen-0.18.0/"
         with_items:
         - ./configure --prefix=/data1/apps-install 
         - /usr/bin/make
         - /usr/bin/make install
